---
- import_role:
    name: aws
  vars:
    dns_record_list:
    - name: "{{ public_dns }}.{{ public_domain }}"
      zone: "{{ public_domain }}"
      type: A
      value: "{{ ec2_instance.public_ip }}"
      ttl: 120
    tags_facts:
      private_dns: "private_dns"
      public_dns: "public_dns"

- name: Nat role
  ansible.builtin.include_role:
    name: nat
    apply:
      tags: configuration
  tags: configuration

- name: Import openvpnas role 
  ansible.builtin.import_role:
    name: inqwise.stacktrek.openvpnas
  vars:
    openvpn_as_host_name: "{{ public_dns }}.{{ public_domain }}"
    openvpn_as_vpn_server_routing_private_networks: ["{{ ec2_instance.vpc_cidr }}"]