---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Get or set the home directory
      block:
        - name: Get system users data
          ansible.builtin.getent:
            database: passwd
            key: keyuser
            split: ":"
      rescue:
        - name: User not found, that's okay
          ansible.builtin.debug:
            msg: "No user found, that is okay."
      always:
        - name: Set home directory to {{ getent_passwd['keyuser'][4] | default('/home') }}
          ansible.builtin.set_fact:
            users_home_base_dir: "{{ getent_passwd['keyuser'][4] | default('/home') }}"

    - name: Record status of .ssh
      ansible.builtin.stat:
        path: "{{ users_home_base_dir }}/keyuser/.ssh"
      register: result
      failed_when:
        - not result.stat.exists

    - name: Check if user notuser does not exist
      ansible.builtin.user:
        name: notuser
        state: absent
      register: users_check_user_notuser
      failed_when:
        - users_check_user_notuser is changed

    - name: Check if unauthorized keys are deleted
      ansible.posix.authorized_key:
        user: root
        state: absent
        key: "ssh-rsa XYZYX54321"
      register: users_check_unauthorized_keys
      failed_when:
        - users_check_unauthorized_keys is changed
