---

- import_role:
    name: aws_utils
    tasks_from: collect_instance_info_speedy

- name: aws tasks complete
  debug: 
    msg: aws postactions
  changed_when: yes
  notify: "aws postactions"
  tags: debug